description: >
  Jekyll theme for nonsensation.com

site_url: localhost:4000
baseurl: ""

title: nonsensation
author:
  name: nonsensation
  email: 3li@nonsensation.com

permalink: /:title

url: "https://www.nonsensation.com"
plugins:
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
  auto_ids: true
  css_class   : 'syntax'
  syntax_highlighter_opts:
    default_lang: text
    span:
      default_lang: text
      line_numbers: false
    block:
      default_lang: text
      # line_numbers: false
      # start_line: 1

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

collections:
  projects:
    output: true
    permalink: /Projects/:path

livereload: true
